(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.PokeBattleLab = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const NATURES = {
    hardy:["Robust",null,null], lonely:["Solo","attack","defense"], brave:["Mutig","attack","speed"], adamant:["Hart","attack","specialAttack"], naughty:["Frech","attack","specialDefense"],
    bold:["Kühn","defense","attack"], docile:["Sanft",null,null], relaxed:["Locker","defense","speed"], impish:["Pfiffig","defense","specialAttack"], lax:["Lasch","defense","specialDefense"],
    timid:["Scheu","speed","attack"], hasty:["Hastig","speed","defense"], serious:["Ernst",null,null], jolly:["Froh","speed","specialAttack"], naive:["Naiv","speed","specialDefense"],
    modest:["Mäßig","specialAttack","attack"], mild:["Mild","specialAttack","defense"], quiet:["Ruhig","specialAttack","speed"], bashful:["Zaghaft",null,null], rash:["Hitzig","specialAttack","specialDefense"],
    calm:["Still","specialDefense","attack"], gentle:["Zart","specialDefense","defense"], sassy:["Forsch","specialDefense","speed"], careful:["Sacht","specialDefense","specialAttack"], quirky:["Kauzig",null,null]
  };
  const TYPE = {
    normal:{rock:.5,ghost:0},fire:{fire:.5,water:.5,grass:2,ice:2,bug:2,rock:.5,dragon:.5},water:{fire:2,water:.5,grass:.5,ground:2,rock:2,dragon:.5},
    electric:{water:2,electric:.5,grass:.5,ground:0,flying:2,dragon:.5},grass:{fire:.5,water:2,grass:.5,poison:.5,ground:2,flying:.5,bug:.5,rock:2,dragon:.5},
    ice:{fire:.5,water:.5,grass:2,ice:.5,ground:2,flying:2,dragon:2},fighting:{normal:2,ice:2,poison:.5,flying:.5,psychic:.5,bug:.5,rock:2,ghost:0},
    poison:{grass:2,poison:.5,ground:.5,rock:.5,ghost:.5},ground:{fire:2,electric:2,grass:.5,poison:2,flying:0,bug:.5,rock:2},flying:{electric:.5,grass:2,fighting:2,bug:2,rock:.5},
    psychic:{fighting:2,poison:2,psychic:.5},bug:{fire:.5,grass:2,fighting:.5,poison:.5,flying:.5,psychic:2,ghost:.5},rock:{fire:2,ice:2,fighting:.5,ground:.5,flying:2,bug:2},
    ghost:{normal:0,psychic:2,ghost:2},dragon:{dragon:2}
  };
  const MOVES = {
    flamethrower:{name:"Flammenwurf",type:"fire",power:90,accuracy:100,category:"special",burn:.1},airSlash:{name:"Luftschnitt",type:"flying",power:75,accuracy:95,category:"special"},
    surf:{name:"Surfer",type:"water",power:90,accuracy:100,category:"special"},iceBeam:{name:"Eisstrahl",type:"ice",power:90,accuracy:100,category:"special"},
    thunderbolt:{name:"Donnerblitz",type:"electric",power:90,accuracy:100,category:"special"},psychic:{name:"Psychokinese",type:"psychic",power:90,accuracy:100,category:"special"},
    shadowBall:{name:"Spukball",type:"ghost",power:80,accuracy:100,category:"special"},sludgeBomb:{name:"Matschbombe",type:"poison",power:90,accuracy:100,category:"special"},
    earthquake:{name:"Erdbeben",type:"ground",power:100,accuracy:100,category:"physical"},rockSlide:{name:"Steinhagel",type:"rock",power:75,accuracy:90,category:"physical"},
    bodySlam:{name:"Bodyslam",type:"normal",power:85,accuracy:100,category:"physical"},dragonClaw:{name:"Drachenklaue",type:"dragon",power:80,accuracy:100,category:"physical"},
    closeCombat:{name:"Nahkampf",type:"fighting",power:120,accuracy:100,category:"physical"},razorLeaf:{name:"Rasierblatt",type:"grass",power:55,accuracy:95,category:"physical"},
    recover:{name:"Genesung",type:"normal",category:"status",heal:.5},thunderWave:{name:"Donnerwelle",type:"electric",category:"status",status:"paralyzed",accuracy:90},
    willOWisp:{name:"Irrlicht",type:"fire",category:"status",status:"burned",accuracy:85},swordsDance:{name:"Schwerttanz",type:"normal",category:"status",boost:{attack:2}}
  };
  const SPECIES = {
    venusaur:{name:"Bisaflor",dexId:3,types:["grass","poison"],base:[80,82,83,100,100,80],nature:"calm",moves:["razorLeaf","sludgeBomb","earthquake"]},
    charizard:{name:"Glurak",dexId:6,types:["fire","flying"],base:[78,84,78,109,85,100],nature:"timid",moves:["flamethrower","airSlash","willOWisp"]},
    blastoise:{name:"Turtok",dexId:9,types:["water"],base:[79,83,100,85,105,78],nature:"modest",moves:["surf","iceBeam"]},
    pikachu:{name:"Pikachu",dexId:25,types:["electric"],base:[35,55,40,50,50,90],nature:"timid",moves:["thunderbolt","thunderWave"]},
    alakazam:{name:"Simsala",dexId:65,types:["psychic"],base:[55,50,45,135,95,120],nature:"timid",moves:["psychic","shadowBall","recover"]},
    machamp:{name:"Machomei",dexId:68,types:["fighting"],base:[90,130,80,65,85,55],nature:"adamant",moves:["closeCombat","rockSlide","earthquake"]},
    gengar:{name:"Gengar",dexId:94,types:["ghost","poison"],base:[60,65,60,130,75,110],nature:"timid",moves:["shadowBall","sludgeBomb","thunderbolt","willOWisp"]},
    rhydon:{name:"Rizeros",dexId:112,types:["ground","rock"],base:[105,130,120,45,45,40],nature:"adamant",moves:["earthquake","rockSlide"]},
    lapras:{name:"Lapras",dexId:131,types:["water","ice"],base:[130,85,80,85,95,60],nature:"calm",moves:["surf","iceBeam","thunderbolt"]},
    snorlax:{name:"Relaxo",dexId:143,types:["normal"],base:[160,110,65,65,110,30],nature:"careful",moves:["bodySlam","earthquake"]},
    jolteon:{name:"Blitza",dexId:135,types:["electric"],base:[65,65,60,110,95,130],nature:"timid",moves:["thunderbolt","shadowBall","thunderWave"]},
    dragonite:{name:"Dragoran",dexId:149,types:["dragon","flying"],base:[91,134,95,100,100,80],nature:"adamant",moves:["dragonClaw","earthquake","rockSlide","swordsDance"]}
  };
  function stats(base,level,natureId){const keys=["hp","attack","defense","specialAttack","specialDefense","speed"],n=NATURES[natureId]||NATURES.hardy;return Object.fromEntries(keys.map((k,i)=>{if(k==="hp")return[k,Math.floor(((2*base[i]+31)*level)/100)+level+10];const mult=n[1]===k?1.1:n[2]===k?.9:1;return[k,Math.floor((Math.floor(((2*base[i]+31)*level)/100)+5)*mult)];}));}
  function effectiveness(type,types){return types.reduce((v,t)=>v*(TYPE[type]?.[t]??1),1);}
  function seeded(seed=1){let x=seed>>>0;return()=>((x=(x*1664525+1013904223)>>>0)/4294967296);}
  function makeMon(id,level=50){const s=SPECIES[id],st=stats(s.base,level,s.nature);return{id,...s,level,stats:st,hp:st.hp,status:null,stages:{attack:0},moves:s.moves.map(x=>MOVES[x])};}
  function expectedDamage(a,d,m){if(!m.power)return 0;const eff=effectiveness(m.type,d.types);if(eff===0)return 0;const atk=m.category==="physical"?a.stats.attack:a.stats.specialAttack,def=m.category==="physical"?d.stats.defense:d.stats.specialDefense;return Math.floor((((2*a.level/5+2)*m.power*atk/def)/50+2)*(a.types.includes(m.type)?1.5:1)*eff*(m.accuracy||100)/100*.925);}
  function statusWorks(move,target){if(move.status==="paralyzed"&&effectiveness("electric",target.types)===0)return false;if(move.status==="burned"&&target.types.includes("fire"))return false;return !target.status;}
  function bestAttack(a,d){return a.moves.map((move,index)=>({move,index,damage:expectedDamage(a,d,move)})).filter(x=>x.move.power).sort((x,y)=>y.damage-x.damage)[0]||{move:a.moves[0],index:0,damage:0};}
  function actsFirst(a,d){return a.stats.speed>d.stats.speed?1:a.stats.speed<d.stats.speed?0:.5;}
  function strategicValue(mon,enemies){if(mon.hp<=0)return 0;let value=mon.hp/mon.stats.hp*30;for(const enemy of enemies.filter(x=>x.hp>0)){const attack=bestAttack(mon,enemy),incoming=bestAttack(enemy,mon);if(attack.damage>=enemy.hp)value+=22;else value+=Math.min(15,attack.damage/Math.max(1,enemy.hp)*15);if(actsFirst(mon,enemy)&&attack.damage>=enemy.hp)value+=12;if(incoming.damage===0)value+=7;}return value;}
  function predictedMove(attacker,defender){let best={index:0,score:-Infinity,damage:0};attacker.moves.forEach((move,index)=>{let score=0,damage=expectedDamage(attacker,defender,move);if(move.power)score=damage+(damage>=defender.hp?90:0);else if(move.heal)score=attacker.hp/attacker.stats.hp<.45?45:0;else if(move.status&&statusWorks(move,defender))score=28;else if(move.boost)score=20;if(score>best.score)best={index,score,damage,move};});return best;}
  function evaluateMove(own,enemy,index){const a=own.team[own.active],d=enemy.team[enemy.active],move=a.moves[index],incoming=predictedMove(d,a),first=actsFirst(a,d);let score=0,reason="";if(move.power){const damage=expectedDamage(a,d,move),koChance=damage>=d.hp;score=damage+(koChance?125:0);if(first===1&&koChance)score+=incoming.damage*.9;if(first===0&&incoming.damage>=a.hp)score-=110;else if(first===.5&&incoming.damage>=a.hp)score-=55;const ownFuture=strategicValue(a,enemy.team),enemyFuture=strategicValue(d,own.team);if(incoming.damage>=a.hp)score-=ownFuture*.7;if(koChance)score+=enemyFuture*.5;reason=`${move.name}: etwa ${damage} Schaden${koChance?", möglicher K.-o.":""}`;}else if(move.heal){const healed=Math.min(a.stats.hp-a.hp,Math.floor(a.stats.hp*move.heal));score=healed-incoming.damage+(a.hp/a.stats.hp<.35?45:0);reason=`${move.name}: ${healed} mögliche Heilung bei ${incoming.damage} erwartetem Gegenschaden`;}else if(move.status){score=statusWorks(move,d)?32: -200;reason=statusWorks(move,d)?`${move.name}: wirksame Statusoption`:`${move.name}: wirkungslos`;}else if(move.boost){score=incoming.damage<a.hp*.35?30:-25;reason=`${move.name}: Aufbau bei ${incoming.damage} erwartetem Gegenschaden`;}return{kind:"move",index,score,reason,incoming:incoming.damage};}
  function evaluateSwitch(own,enemy,index,stateTurn){const active=own.team[own.active],target=own.team[index],opponent=enemy.team[enemy.active],incoming=predictedMove(opponent,target),best=bestAttack(target,opponent),activeBest=bestAttack(active,opponent),activeIncoming=predictedMove(opponent,active),targetValue=strategicValue(target,enemy.team),activeValue=strategicValue(active,enemy.team);let score=best.damage-incoming.damage*1.25-28;const activeCanAct=actsFirst(active,opponent)>0&&activeIncoming.damage<active.hp;if(activeCanAct&&activeBest.damage>0)score-=activeBest.damage*.75;if(incoming.damage>=target.hp)score-=220;if(best.damage>=opponent.hp&&incoming.damage<target.hp)score+=80;if(active.hp<=activeIncoming.damage&&activeValue>targetValue+15&&incoming.damage<target.hp*.5)score+=55;if(activeBest.damage===0&&best.damage>0&&incoming.damage<target.hp)score+=115;if(Number.isFinite(own.lastSwitchTurn)&&stateTurn-own.lastSwitchTurn<=2)score-=65;score+=(activeValue-targetValue)*.35;return{kind:"switch",index,score,incoming:incoming.damage,reason:`${target.name}: etwa ${best.damage} Gegenschaden, kassiert voraussichtlich ${incoming.damage}${incoming.damage>=target.hp?" (K.-o.-Risiko)":""}`};}
  function choose(state,side){const own=state[side],enemy=state[side?0:1],a=own.team[own.active];const choices=a.moves.map((_,i)=>evaluateMove(own,enemy,i));own.team.forEach((mon,i)=>{if(i!==own.active&&mon.hp>0)choices.push(evaluateSwitch(own,enemy,i,state.turn||0));});choices.sort((x,y)=>y.score-x.score);return{...choices[0],alternatives:choices.slice(1,3)};}
  function firstAlive(side){return side.team.findIndex(m=>m.hp>0);}
  function chooseReplacement(own,enemy){let best=null;own.team.forEach((mon,index)=>{if(mon.hp<=0)return;const attack=bestAttack(mon,enemy),incoming=bestAttack(enemy,mon),value=strategicValue(mon,[enemy]);let score=attack.damage-incoming.damage+(attack.damage>=enemy.hp?90:0)+(actsFirst(mon,enemy)?15:0)+value*.25;if(!best||score>best.score)best={index,mon,score,attack,incoming};});return best;}
  function resolveForcedReplacements(state,log,turn){for(let side=0;side<2;side++){const own=state[side],enemy=state[side?0:1];if(firstAlive(own)<0||own.team[own.active].hp>0)continue;const pick=chooseReplacement(own,enemy.team[enemy.active]);if(!pick)continue;own.active=pick.index;log.push({turn,text:`${own.name} schickt ${pick.mon.name} in den Kampf (Prognose: ${pick.attack.move.name}, etwa ${pick.attack.damage} Schaden; erwarteter Gegenschaden ${pick.incoming.damage}).`});}}
  function executeMove(attacker,defender,move,random,log,turn){if(random()*100>(move.accuracy||100)){log.push({turn,text:`${attacker.name}s ${move.name} geht daneben.`});return;}if(move.heal){const amount=Math.min(attacker.stats.hp-attacker.hp,Math.floor(attacker.stats.hp*move.heal));attacker.hp+=amount;log.push({turn,text:`${attacker.name} setzt ${move.name} ein und heilt ${amount} KP.`});return;}if(move.status){if(!statusWorks(move,defender)){log.push({turn,text:`${attacker.name} setzt ${move.name} ein – es hat keine Wirkung auf ${defender.name}.`});return;}defender.status=move.status;log.push({turn,text:`${attacker.name} setzt ${move.name} ein. ${defender.name} wird ${move.status==="burned"?"verbrannt":"paralysiert"}.`});return;}if(move.boost){attacker.stages.attack=Math.min(6,attacker.stages.attack+2);attacker.stats.attack=Math.floor(attacker.stats.attack*1.5);log.push({turn,text:`${attacker.name} setzt ${move.name} ein. Angriff steigt stark.`});return;}const eff=effectiveness(move.type,defender.types);if(eff===0){log.push({turn,text:`${attacker.name} setzt ${move.name} ein – es hat keine Wirkung auf ${defender.name}.`});return;}const damage=Math.floor(expectedDamage(attacker,defender,{...move,accuracy:100})*(.85+random()*.15)/.925);defender.hp=Math.max(0,defender.hp-damage);log.push({turn,text:`${attacker.name} setzt ${move.name} ein: ${damage} Schaden${eff>1?" – sehr effektiv!":eff<1?" – nicht sehr effektiv.":"."}`});if(defender.hp===0)log.push({turn,text:`${defender.name} ist kampfunfähig!`});}
  function simulate(options={}){const random=seeded(Number(options.seed)||2026),ids=Object.keys(SPECIES),state=[{name:"Team Blau",team:(options.teamA||ids.slice(0,3)).map(id=>makeMon(id)),active:0,lastSwitchTurn:-99},{name:"Team Rot",team:(options.teamB||ids.slice(3,6)).map(id=>makeMon(id)),active:0,lastSwitchTurn:-99}],log=[];for(let turn=1;turn<=100;turn++){state.turn=turn;if(firstAlive(state[0])<0||firstAlive(state[1])<0)break;resolveForcedReplacements(state,log,turn);if(firstAlive(state[0])<0||firstAlive(state[1])<0)break;const actions=[choose(state,0),choose(state,1)];log.push({turn,text:`Zug ${turn}`});const order=[0,1].sort((x,y)=>{if(actions[x].kind==="switch"&&actions[y].kind!=="switch")return-1;if(actions[y].kind==="switch"&&actions[x].kind!=="switch")return 1;const sx=state[x].team[state[x].active].stats.speed,sy=state[y].team[state[y].active].stats.speed;return sx===sy?(random()<.5?-1:1):sy-sx;});for(const side of order){const own=state[side],enemy=state[side?0:1],action=actions[side],plannedActor=own.team[own.active];if(plannedActor.hp<=0||firstAlive(enemy)<0)continue;if(action.kind==="switch"){const target=own.team[action.index];if(!target||target.hp<=0)continue;own.active=action.index;own.lastSwitchTurn=turn;log.push({turn,text:`${plannedActor.name} wird gegen ${target.name} ausgewechselt (${action.reason}).`});continue;}const defender=enemy.team[enemy.active];if(defender.hp<=0)continue;executeMove(plannedActor,defender,plannedActor.moves[action.index]||plannedActor.moves[0],random,log,turn);}for(const side of state)for(const mon of side.team)if(mon.hp>0&&mon.status==="burned"){const dot=Math.max(1,Math.floor(mon.stats.hp/16));mon.hp=Math.max(0,mon.hp-dot);log.push({turn,text:`${mon.name} erleidet ${dot} Verbrennungsschaden.`});if(mon.hp===0)log.push({turn,text:`${mon.name} ist kampfunfähig!`});}}const winner=firstAlive(state[0])>=0&&firstAlive(state[1])<0?0:firstAlive(state[1])>=0&&firstAlive(state[0])<0?1:null;return{state,log,winner,seed:Number(options.seed)||2026};}
  return{NATURES,MOVES,SPECIES,stats,effectiveness,simulate,expectedDamage,choose,strategicValue};
});
